name: .NET Core

on: pull_request

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Test
      run:
        dotnet test ./SFX.Crypto.sln --configuration Release 
        # dotnet test ./tst/Crypto.CSharp.Tests/Crypto.CSharp.Tests.csproj
        # dotnet test ./tst/Crypto.Windows.CSharp.Tests/Crypto.Windows.CSharp.Tests.csproj
        # dotnet test ./tst/Crypto.Tests/Crypto.Tests.fsproj
        # dotnet test ./tst/Crypto.Windows.Tests/Crypto.Windows.Tests.fsproj
    - name: Build NuGet Packages
      run: 
        dotnet pack ./SFX.Crypto.sln --configuration Release -o ./nuget
        # dotnet pack ./src/Crypto.CSharp/Crypto.CSharp.csproj --configuration Release -o ./nuget
        # dotnet pack ./src/Crypto.Windows.CSharp/Crypto.Windows.CSharp.csproj --configuration Release -o ./nuget
        # dotnet pack ./src/Crypto/Crypto.fsproj --configuration Release -o ./nuget
        # dotnet pack ./src/Crypto.Windows/Crypto.Windows.fsproj --configuration Release -o ./nuget
    - name: Deploy NuGet Packages
      run: 
        # dotnet nuget push D:\a\SFX.Crypto/SFX.Crypto/nuget/SFX.Crypto.CSharp.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
        # dotnet nuget push D:\a\SFX.Crypto\SFX.Crypto\nuget\SFX.Crypto.Windows.CSharp.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
        dotnet nuget push D:\a\SFX.Crypto/SFX.Crypto/nuget/SFX.Crypto.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
        # dotnet nuget push D:\a\SFX.Crypto\SFX.Crypto\nuget\SFX.Crypto.Windows.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
